title: glucolte
description: notes • principles • systems
url: https://glucolte.github.io
baseurl: ""          # user site → keep empty
markdown: kramdown
kramdown:
  input: GFM
  toc_levels: 2..3   # include ## and ### in the ToC

highlighter: rouge

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Set default layouts for different sections
defaults:
  # Home page uses home layout
  - scope:
      path: ""
      type: "pages"
      name: "index"
    values:
      layout: "home"
  
  # Study pages use study layout
  - scope:
      path: "study"
      type: "pages"
    values:
      layout: "study"
  
  # Everything else uses default layout
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
