title: glucolte
description: notes • principles • systems
url: https://glucolte.github.io
baseurl: ""          # user site → keep empty
markdown: kramdown

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# All Markdown pages use our layout by default
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
